
---
title: "Looking at Nobel Data"
author: "By Tony Fraser"
date: "November 5 2023"
format:
  pdf: 
    latex-engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r messages=FALSE, warning=FALSE, output=FALSE}
library(httr)
library(jsonlite)
library(dplyr)
library(uuid)
library(tidyr)
library(ggplot2)


get_data <- function(suffix, type = "json", persist = FALSE) {
  base_url <- "http://api.nobelprize.org/v1/"
  full_url <- paste0(base_url, suffix)
  accept_header <- ifelse(type == "json", "application/json", "text/csv")
  response <- GET(full_url, accept(accept_header))
  if (status_code(response) == 200) {
    content_data <- content(response, "text", encoding = "UTF-8")
    if (persist) {
      file_name <- paste0("nogit_", UUIDgenerate(), "_", suffix, 
            ifelse(type == "json", ".json", ".csv"))
      print(sprintf("FileName %s", file_name))
      write(content_data, file_name)
    }
    if (type == "json") {return(fromJSON(content_data))} 
    else if (type == "csv") 
        {return(read.csv(text = content_data, stringsAsFactors = FALSE))} 
    else {stop("Type must be either 'json' or 'csv'.")}
  } else {
    stop("Failed to retrieve data: ", status_code(response))
  }
}
``` 


```{r}
countries <- get_data(suffix = "country.csv", type = "csv", persist = FALSE)
people <-  get_data(suffix = "prize.json", type = "json", persist = TRUE) %>%
  { flatten(. $prizes) } %>%
  unnest(laureates)

```

### Question 1
How many people are submitted for category? I'd like to see a simple groupby/count. 

```{r}
people %>%
  group_by(category) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  ggplot(aes(x = reorder(category, count), y = count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x = "Count of People", y = "Category", title = "Count of People by Nobel Category") +
  theme_minimal()

```



